<x-guest-layout>
    <div class="mx-auto flex min-h-screen max-w-7xl items-center px-4 py-8 sm:px-6 lg:px-8">
        <div class="grid w-full overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-2xl shadow-slate-900/10 dark:border-slate-700 dark:bg-slate-900 lg:grid-cols-5">
            <section class="relative hidden overflow-hidden bg-slate-950 p-10 text-white lg:col-span-2 lg:flex lg:min-h-[44rem] lg:flex-col">
                <div aria-hidden="true" class="absolute inset-0 bg-[radial-gradient(circle_at_top_right,_rgba(59,130,246,0.5),_transparent_44%),radial-gradient(circle_at_bottom_left,_rgba(34,211,238,0.25),_transparent_42%)]"></div>
                <div class="relative flex items-center gap-3"><span class="flex h-11 w-11 items-center justify-center rounded-2xl bg-blue-600 shadow-lg shadow-blue-900/50"><svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8"><path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12l8.954-8.955a1.5 1.5 0 012.122 0L22.28 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" /></svg></span><div><p class="font-bold tracking-tight">WFH Tracker</p><p class="text-xs text-slate-400">Workforce workspace</p></div></div>
                <div class="relative my-auto py-12"><p class="text-xs font-bold uppercase tracking-[0.2em] text-blue-300">Get started</p><h1 class="mt-4 text-4xl font-bold tracking-tight">Your workday, in one place.</h1><p class="mt-4 max-w-sm text-sm leading-6 text-slate-300">Create your profile to stay organized with attendance, schedules, requests, and accomplishments.</p></div>
                <div class="relative rounded-2xl border border-white/10 bg-white/5 p-5"><p class="text-sm font-semibold">A clearer daily workflow</p><p class="mt-2 text-sm leading-6 text-slate-300">Plan work, record your day, and keep your team up to date without switching tools.</p></div>
            </section>

            <section class="flex items-center px-6 py-10 sm:px-12 lg:col-span-3 lg:px-16">
                <div class="mx-auto w-full max-w-xl">
                    <div class="mb-8"><div class="mb-6 flex items-center gap-3 lg:hidden"><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-600 text-white"><svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8"><path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12l8.954-8.955a1.5 1.5 0 012.122 0L22.28 12" /></svg></span><span class="font-bold text-slate-900 dark:text-white">WFH Tracker</span></div><p class="text-xs font-bold uppercase tracking-[0.18em] text-blue-600">Create account</p><h1 class="mt-2 text-3xl font-bold tracking-tight text-slate-900 dark:text-white">Join your workspace</h1><p class="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-300">Set up your profile to start planning and recording your workday.</p></div>

                    @if ($errors->any())
                        <div class="mb-6 rounded-xl border border-rose-200 bg-rose-50 p-4 dark:border-rose-500/40 dark:bg-rose-950/40"><ul class="list-inside list-disc space-y-1 text-sm text-rose-700 dark:text-rose-200">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>
                    @endif

                    <form method="POST" action="{{ route('register') }}" class="grid gap-5 sm:grid-cols-2">
                        @csrf
                        <label class="block sm:col-span-2"><span class="mb-2 block text-sm font-semibold text-slate-700 dark:text-slate-200">Full name</span><input id="name" type="text" name="name" value="{{ old('name') }}" required autofocus autocomplete="name" placeholder="Enter your full name" class="w-full rounded-xl border-slate-300 px-4 py-3 text-sm shadow-sm transition placeholder:text-slate-400 focus:border-blue-500 focus:ring-blue-500 dark:border-slate-600"></label>
                        <label class="block sm:col-span-2"><span class="mb-2 block text-sm font-semibold text-slate-700 dark:text-slate-200">Email address</span><input id="email" type="email" name="email" value="{{ old('email') }}" required autocomplete="username" placeholder="you@company.com" class="w-full rounded-xl border-slate-300 px-4 py-3 text-sm shadow-sm transition placeholder:text-slate-400 focus:border-blue-500 focus:ring-blue-500 dark:border-slate-600"></label>
                        <label class="block"><span class="mb-2 block text-sm font-semibold text-slate-700 dark:text-slate-200">Department</span><select name="department_id" required class="w-full rounded-xl border-slate-300 px-4 py-3 text-sm shadow-sm transition focus:border-blue-500 focus:ring-blue-500 dark:border-slate-600"><option value="">Select a department</option>@foreach (\App\Models\Department::all() as $department)<option value="{{ $department->id }}" @selected(old('department_id') == $department->id)>{{ $department->name }}</option>@endforeach</select></label>
                        <label class="block"><span class="mb-2 block text-sm font-semibold text-slate-700 dark:text-slate-200">Role</span><select name="role" required class="w-full rounded-xl border-slate-300 px-4 py-3 text-sm shadow-sm transition focus:border-blue-500 focus:ring-blue-500 dark:border-slate-600"><option value="">Select a role</option><option value="employee" @selected(old('role') === 'employee')>Employee</option><option value="supervisor" @selected(old('role') === 'supervisor')>Supervisor</option><option value="admin" @selected(old('role') === 'admin')>Admin</option></select></label>
                        <div x-data="{ show: false }" class="block"><label for="password" class="mb-2 block text-sm font-semibold text-slate-700 dark:text-slate-200">Password</label><div class="relative"><input :type="show ? 'text' : 'password'" id="password" name="password" required autocomplete="new-password" placeholder="Create a password" class="w-full rounded-xl border-slate-300 px-4 py-3 pr-12 text-sm shadow-sm transition placeholder:text-slate-400 focus:border-blue-500 focus:ring-blue-500 dark:border-slate-600"><button type="button" @click="show = !show" x-bind:aria-label="show ? 'Hide password' : 'Show password'" class="absolute inset-y-0 right-0 flex w-12 items-center justify-center text-slate-400 transition hover:text-blue-600"><svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.7"><path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z" /><path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" /></svg></button></div></div>
                        <div x-data="{ show: false }" class="block"><label for="password_confirmation" class="mb-2 block text-sm font-semibold text-slate-700 dark:text-slate-200">Confirm password</label><div class="relative"><input :type="show ? 'text' : 'password'" id="password_confirmation" name="password_confirmation" required autocomplete="new-password" placeholder="Repeat your password" class="w-full rounded-xl border-slate-300 px-4 py-3 pr-12 text-sm shadow-sm transition placeholder:text-slate-400 focus:border-blue-500 focus:ring-blue-500 dark:border-slate-600"><button type="button" @click="show = !show" x-bind:aria-label="show ? 'Hide password' : 'Show password'" class="absolute inset-y-0 right-0 flex w-12 items-center justify-center text-slate-400 transition hover:text-blue-600"><svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.7"><path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z" /><path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" /></svg></button></div></div>
                        <div class="sm:col-span-2"><button type="submit" class="inline-flex w-full items-center justify-center rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white shadow-lg shadow-blue-600/20 transition hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 dark:focus:ring-offset-slate-900">Create account</button><p class="mt-6 text-center text-sm text-slate-500 dark:text-slate-300">Already have an account? <a href="{{ route('login') }}" class="font-semibold text-blue-600 hover:text-blue-700">Sign in</a></p></div>
                    </form>
                </div>
            </section>
        </div>
    </div>
</x-guest-layout>
