<x-dashboard-layout title="Attendance Corrections">
    <div class="mx-auto max-w-5xl space-y-6 pb-6">
        <section class="flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white px-6 py-7 shadow-sm sm:flex-row sm:items-center sm:justify-between">
            <div><p class="text-xs font-bold uppercase tracking-[0.16em] text-blue-600">Attendance</p><h1 class="mt-1 text-2xl font-bold tracking-tight text-slate-900">Request an attendance correction</h1><p class="mt-2 max-w-2xl text-sm text-slate-600">Correct a recorded time. Your attendance is changed only after supervisor approval.</p></div>
            <a href="{{ route('attendance.daily') }}" class="inline-flex items-center justify-center rounded-lg border border-slate-300 bg-white px-4 py-3 text-sm font-semibold text-slate-700 transition hover:border-blue-300 hover:bg-blue-50 hover:text-blue-700">View attendance history</a>
        </section>

        @if (session('correction_success'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800">{{ session('correction_success') }}</div>@endif
        @if (session('correction_error'))<div class="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-medium text-rose-800">{{ session('correction_error') }}</div>@endif

        <div class="grid gap-6 lg:grid-cols-[minmax(0,1fr)_17rem]">
            <section class="max-w-3xl rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 px-6 py-5"><h2 class="text-lg font-bold text-slate-900">Correction details</h2><p class="mt-1 text-sm text-slate-500">Choose the workday, then enter the time that should change.</p></div>
                <form method="POST" action="{{ route('attendance.corrections.store') }}" enctype="multipart/form-data" class="max-w-2xl space-y-5 p-6">@csrf
                    <div><label for="attendance_id" class="text-sm font-semibold text-slate-800">Attendance record</label><select id="attendance_id" name="attendance_id" required class="mt-2 w-full rounded-lg border-slate-300 text-sm text-slate-800 shadow-sm focus:border-blue-500 focus:ring-blue-500"><option value="">Select a recorded workday</option>@foreach ($attendances as $attendance)<option value="{{ $attendance->id }}" @selected((string) old('attendance_id', $selectedAttendanceId) === (string) $attendance->id)>{{ $attendance->date->format('D, M j, Y') }} · {{ $attendance->formattedTimeIn() ?? 'No time in' }} – {{ $attendance->formattedTimeOut() ?? 'No time out' }}</option>@endforeach</select>@error('attendance_id')<p class="mt-2 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
                    @if ($selectedAttendanceId && $attendances->firstWhere('id', $selectedAttendanceId)?->hasMissingClockOut())<div class="rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800"><span class="font-semibold">Missing clock-out:</span> enter the actual time out and a short reason. It will remain pending until approved.</div>@endif
                    <div class="grid gap-5 sm:grid-cols-2">
                        <div>
                            <label class="text-sm font-semibold text-slate-800">Corrected time in <span class="font-normal text-slate-400">(if needed)</span></label>
                            <div class="mt-2"><x-wfh-time-picker name="requested_time_in" :value="old('requested_time_in')" /></div>
                            @error('requested_time_in')<p class="mt-2 text-sm text-rose-600">{{ $message }}</p>@enderror
                        </div>
                        <div>
                            <label class="text-sm font-semibold text-slate-800">Corrected time out <span class="font-normal text-slate-400">(if needed)</span></label>
                            <div class="mt-2"><x-wfh-time-picker name="requested_time_out" :value="old('requested_time_out')" /></div>
                            @error('requested_time_out')<p class="mt-2 text-sm text-rose-600">{{ $message }}</p>@enderror
                        </div>
                    </div>
                    <div><label for="reason" class="text-sm font-semibold text-slate-800">Reason for correction</label><textarea id="reason" name="reason" rows="4" required maxlength="1000" class="mt-2 w-full rounded-lg border-slate-300 text-sm text-slate-800 shadow-sm focus:border-blue-500 focus:ring-blue-500" placeholder="For example: My internet connection dropped while I was clocking out.">{{ old('reason') }}</textarea>@error('reason')<p class="mt-2 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
                    <div><label for="supporting_document" class="text-sm font-semibold text-slate-800">Supporting proof <span class="font-normal text-slate-400">(optional)</span></label><input id="supporting_document" name="supporting_document" type="file" accept=".pdf,.doc,.docx,.jpg,.jpeg,.png" class="mt-2 block w-full text-sm text-slate-600 file:mr-4 file:rounded-lg file:border-0 file:bg-blue-600 file:px-4 file:py-2.5 file:text-sm file:font-semibold file:text-white hover:file:bg-blue-700"><p class="mt-2 text-xs text-slate-500">Upload a PDF, Word document, JPG, or PNG up to 2 MB.</p>@error('supporting_document')<p class="mt-2 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
                    <div class="flex justify-end border-t border-slate-100 pt-5"><button type="submit" class="rounded-lg bg-blue-600 px-5 py-3 text-sm font-semibold text-white shadow-sm transition hover:bg-blue-700">Submit correction</button></div>
                </form>
            </section>
            <aside class="h-fit rounded-2xl bg-slate-900 p-6 text-white shadow-sm"><p class="text-xs font-bold uppercase tracking-[0.16em] text-blue-300">How it works</p><h2 class="mt-3 text-xl font-bold">Keep your record accurate.</h2><ol class="mt-6 space-y-5 text-sm leading-6 text-slate-200"><li class="flex gap-3"><span class="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-slate-700 text-xs font-bold">1</span><span>Choose the workday with the incorrect record.</span></li><li class="flex gap-3"><span class="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-slate-700 text-xs font-bold">2</span><span>Provide the correct time and a clear reason.</span></li><li class="flex gap-3"><span class="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-slate-700 text-xs font-bold">3</span><span>Only an approved request updates attendance.</span></li></ol></aside>
        </div>

        <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 px-6 py-5"><h2 class="text-lg font-bold text-slate-900">Your correction requests</h2><p class="mt-1 text-sm text-slate-500">Every request and decision is retained here.</p></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th class="px-6 py-3">Workday</th><th class="px-6 py-3">Requested change</th><th class="px-6 py-3">Reason</th><th class="px-6 py-3">Proof</th><th class="px-6 py-3">Status</th><th class="px-6 py-3">Review note</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($corrections as $correction)<tr class="align-top text-slate-700"><td class="whitespace-nowrap px-6 py-4 font-semibold text-slate-800">{{ $correction->attendance->date->format('M j, Y') }}</td><td class="whitespace-nowrap px-6 py-4">{{ $correction->requested_time_in ? date('g:i A', strtotime($correction->requested_time_in)) : '—' }} <span class="text-slate-400">/</span> {{ $correction->requested_time_out ? date('g:i A', strtotime($correction->requested_time_out)) : '—' }}</td><td class="max-w-xs px-6 py-4 text-slate-600">{{ $correction->reason }}</td><td class="px-6 py-4">@if ($correction->supporting_document)<a href="{{ route('attendance.corrections.supporting-document', $correction) }}" class="font-semibold text-blue-700 hover:text-blue-900">Download proof</a>@else<span class="text-slate-400">—</span>@endif</td><td class="px-6 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $correction->status === 'approved' ? 'bg-emerald-50 text-emerald-700' : ($correction->status === 'rejected' ? 'bg-rose-50 text-rose-700' : 'bg-amber-50 text-amber-700') }}">{{ ucfirst($correction->status) }}</span></td><td class="max-w-xs px-6 py-4 text-slate-600">{{ $correction->remarks ?: '—' }}</td></tr>@empty<tr><td colspan="6" class="px-6 py-14 text-center text-slate-500">No attendance corrections have been submitted.</td></tr>@endforelse</tbody></table></div></section>
    </div>
</x-dashboard-layout>
